name: Build packages
on:
  push:
    branches:
    - main
  pull_request: {}
  release:
    types: [released, prereleased]
  workflow_dispatch:
jobs:
  exe:
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: 3.9
    - name: Install deps
      run: |
        pip install -U pip wheel setuptools
        pip install .[all]
        pip install -r scripts/build-requirements.txt
    - name: Pull images
      run: |
        dvc pull -vv
    - name: Build
      run: python scripts\build.py exe
      shell: cmd
    - name: Publish
      if: github.event_name == 'release'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      uses: actions/upload-release-asset@v1.0.2
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: scripts/innosetup/dvc-${{ github.event.release.tag_name }}.exe
        asset_name: dvc-${{ github.event.release.tag_name }}.exe
        asset_content_type: binary/octet-stream
